name: Main

on:
       
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/test-01.yml'
   
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.all_TOKEN }}
        with:
          name: 456
          tag_name: /*-          
          files: Release.txt
